services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-123}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_DB: ${DB_NAME:-drogueria_db}
    container_name: drogueria-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - drogueria-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mi-backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-drogueria_db}
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-123}
      SECRET: ${SECRET:-secreto}
      EXPIRES: ${EXPIRES:-96h}
    depends_on:
      - db
    networks:
      - drogueria-network

networks:
  drogueria-network:
    driver: bridge

volumes:
  postgres_data:
